// ── R-Tracker Path Planner — Code Generation ─────────────────────────────

// Emits a Pedro Pathing 3 path class: poses from a PoseFactory in degrees, one method per
// segment returning a Path built with Paths.line()/curve() and a linear heading interpolation,
// and fullPath() joining them. Headings are stored in Pedro's convention (0 = +x, CCW), so the
// number in the editor is the number Pedro gets.
function updateCode() {
  const block = document.getElementById('codeBlock');
  if (waypoints.length < 2) {
    block.textContent = '// Add at least 2 waypoints to generate code';
    return;
  }
  // Control poses only shape the curve; Pedro ignores their heading, so it is 0.
  const ctrl = cp => `p.of(${cp.x.toFixed(2)}, ${cp.y.toFixed(2)}, 0)`;
  const whole = segments.length >= 2 ? 'fullPath' : 'path1';
  const L = [];
  L.push('package org.firstinspires.ftc.teamcode.paths;');
  L.push('');
  L.push('import static com.pedropathing.api.Paths.*;');
  L.push('');
  L.push('import com.pedropathing.api.PoseFactory;');
  L.push('import com.pedropathing.math.Pose;');
  L.push('import com.pedropathing.paths.Path;');
  L.push('');
  L.push('// Generated by R-Tracker. Pedro Pathing 3: inches, heading in degrees (0 = +x, counter-clockwise).');
  L.push(`// Follow with Ivy:  schedule(follow(follower, ${whole}()));`);
  L.push('public class AutoPath {');
  // The factory must be declared before the poses: Java runs field initialisers in order.
  L.push('    private final PoseFactory p = PoseFactory.degrees();');
  L.push('');
  waypoints.forEach((wp, i) => {
    L.push(`    public final Pose point${i+1} = p.of(${wp.x.toFixed(2)}, ${wp.y.toFixed(2)}, ${wp.heading.toFixed(1)});`);
  });
  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i];
    const a = `point${i+1}`, b = `point${i+2}`;
    const end = waypoints[i + 1];
    L.push('');
    if (end.waitMs > 0) {
      L.push(`    // Wait ${end.waitMs}ms at ${b}${end.action !== 'None' ? ` (${end.action})` : ''}`);
    }
    const shape = seg.cps.length === 0
      ? `line(${a}, ${b})`
      : `curve(${a}, ${seg.cps.map(ctrl).join(', ')}, ${b})`;
    L.push(`    public Path path${i+1}() {`);
    L.push(`        return ${shape}.linear(${a}, ${b});`);
    L.push(`    }`);
  }
  if (segments.length >= 2) {
    L.push('');
    L.push('    public Path fullPath() {');
    L.push(`        return path(${segments.map((_, i) => `path${i+1}()`).join(', ')});`);
    L.push('    }');
  }
  L.push('}');
  block.textContent = L.join('\n');
}

function copyCode() {
  const text = document.getElementById('codeBlock').textContent;
  navigator.clipboard.writeText(text).then(() => {
    const btn = document.getElementById('copyBtn');
    btn.textContent = '✓ Copied!'; btn.classList.add('copied');
    setTimeout(() => { btn.textContent = 'Copy Code'; btn.classList.remove('copied'); }, 2000);
  });
}

function exportPath() {
  const data = JSON.stringify({ waypoints, segments, pathSettings }, null, 2);
  const blob = new Blob([data], { type: 'application/json' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url; a.download = 'path.json'; a.click();
  URL.revokeObjectURL(url);
}
