// ── R-Tracker Path Planner — Code Generation ─────────────────────────────

// Emits a Pedro Pathing 3 path class: poses from a PoseFactory in degrees, one method per
// segment returning a Path built with Paths.line()/curve() and a linear heading interpolation,
// fullPath() joining them, and routine(follower): an Ivy command that follows each segment in
// turn and runs every waypoint's wait (waitMs) and action (an instant() with a TODO for the
// team's own mechanism code) where the robot reaches it. Headings are stored in Pedro's
// convention (0 = +x, CCW), so the number in the editor is the number Pedro gets.
const ACTION_TODO = {
  Intake:  'start your intake',
  Outtake: 'run your outtake',
  Custom:  'your action',
};

// The Ivy steps for arriving at a waypoint: its action, then its wait.
function stopSteps(wp, name) {
  const out = [];
  const todo = ACTION_TODO[wp.action];
  if (todo) out.push(`instant(() -> { /* TODO (${name}): ${todo} */ })`);
  if (wp.waitMs > 0) out.push(`waitMs(${Math.round(wp.waitMs)})`);
  return out;
}

function updateCode() {
  const block = document.getElementById('codeBlock');
  if (waypoints.length < 2) {
    block.textContent = '// Add at least 2 waypoints to generate code';
    return;
  }
  // Control poses only shape the curve; Pedro ignores their heading, so it is 0.
  const ctrl = cp => `p.of(${cp.x.toFixed(2)}, ${cp.y.toFixed(2)}, 0)`;
  const whole = segments.length >= 2 ? 'fullPath' : 'path1';
  const L = [];
  L.push('package org.firstinspires.ftc.teamcode.paths;');
  L.push('');
  L.push('import static com.pedropathing.api.Paths.*;');
  L.push('import static com.pedropathing.ivy.commands.Commands.*;');
  L.push('import static com.pedropathing.ivy.groups.Groups.*;');
  L.push('import static com.pedropathing.ivy.pedro.PedroCommands.*;');
  L.push('');
  L.push('import com.pedropathing.api.PoseFactory;');
  L.push('import com.pedropathing.follower.Follower;');
  L.push('import com.pedropathing.ivy.Command;');
  L.push('import com.pedropathing.math.Pose;');
  L.push('import com.pedropathing.paths.Path;');
  L.push('');
  L.push('// Generated by R-Tracker. Pedro Pathing 3: inches on the 141.5 in field, heading in degrees (0 = +x, counter-clockwise).');
  L.push('// Run the whole auto (paths, waits and actions) with Ivy:  schedule(new AutoPath().routine(follower));');
  L.push(`// Or only the path:  schedule(follow(follower, ${whole}()));`);
  L.push('public class AutoPath {');
  // The factory must be declared before the poses: Java runs field initialisers in order.
  L.push('    private final PoseFactory p = PoseFactory.degrees();');
  L.push('');
  waypoints.forEach((wp, i) => {
    L.push(`    public final Pose point${i+1} = p.of(${wp.x.toFixed(2)}, ${wp.y.toFixed(2)}, ${wp.heading.toFixed(1)});`);
  });
  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i];
    const a = `point${i+1}`, b = `point${i+2}`;
    L.push('');
    const shape = seg.cps.length === 0
      ? `line(${a}, ${b})`
      : `curve(${a}, ${seg.cps.map(ctrl).join(', ')}, ${b})`;
    L.push(`    public Path path${i+1}() {`);
    L.push(`        return ${shape}.linear(${a}, ${b});`);
    L.push(`    }`);
  }
  if (segments.length >= 2) {
    L.push('');
    L.push('    public Path fullPath() {');
    L.push(`        return path(${segments.map((_, i) => `path${i+1}()`).join(', ')});`);
    L.push('    }');
  }
  // routine(): every segment in order, with each waypoint's action and wait where it is reached.
  const steps = stopSteps(waypoints[0], 'point1');
  for (let i = 0; i < segments.length; i++) {
    steps.push(`follow(follower, path${i+1}())`);
    steps.push(...stopSteps(waypoints[i + 1], `point${i+2}`));
  }
  L.push('');
  L.push('    // Actions are TODO slots: replace each comment with your mechanism code.');
  L.push('    public Command routine(Follower follower) {');
  L.push('        return sequential(');
  steps.forEach((st, k) => L.push(`            ${st}${k < steps.length - 1 ? ',' : ''}`));
  L.push('        );');
  L.push('    }');
  L.push('}');
  block.textContent = L.join('\n');
}

function copyCode() {
  const text = document.getElementById('codeBlock').textContent;
  navigator.clipboard.writeText(text).then(() => {
    const btn = document.getElementById('copyBtn');
    btn.textContent = 'Copied'; btn.classList.add('copied');
    setTimeout(() => { btn.textContent = 'Copy Code'; btn.classList.remove('copied'); }, 2000);
  });
}

function exportPath() {
  const data = JSON.stringify({ waypoints, segments, pathSettings }, null, 2);
  const blob = new Blob([data], { type: 'application/json' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url; a.download = 'path.json'; a.click();
  URL.revokeObjectURL(url);
}
